nodeVersion: 24.18.0
engineStrict: true
savePrefix: ''

verifyDepsBeforeRun: error
enableGlobalVirtualStore: false
strictDepBuilds: true
onlyBuiltDependencies:
  - 'esbuild'

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
trustLockfile: false
blockExoticSubdeps: true
