nodeVersion: 24.18.0
engineStrict: true
savePrefix: ''

verifyDepsBeforeRun: error
enableGlobalVirtualStore: false
strictDepBuilds: true
onlyBuiltDependencies:
  - 'esbuild'

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - '@iconify-json/lucide@1.2.118'
  - '@tailwindcss/node@4.3.3'
  - '@tailwindcss/oxide@4.3.3'
  - '@tailwindcss/oxide-android-arm64@4.3.3'
  - '@tailwindcss/oxide-darwin-arm64@4.3.3'
  - '@tailwindcss/oxide-darwin-x64@4.3.3'
  - '@tailwindcss/oxide-freebsd-x64@4.3.3'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.3'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.3'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.3'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.3'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.3'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.3'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.3'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.3'
  - '@tailwindcss/vite@4.3.3'
  - 'tailwindcss@4.3.3'
  - 'vite@8.1.5'

trustPolicy: no-downgrade
trustLockfile: false
blockExoticSubdeps: true
